name: Build pull request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev

permissions:
  contents: read

jobs:
  release:
    name: Build
    if: github.repository_owner == 'anddea'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v3

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build --no-daemon
